### PR TITLE
Change wp-cli to standard installation

### LINKED ISSUE #983: Unable to update wp-cli on provision
In provision.sh, wp-cli gets [updated like this](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L591):

```
cd /srv/www/wp-cli
git pull --rebase origin master
composer update
```

This will work the first time that wp-cli is updated on provision. However, `composer update` modifies the `composer.lock` file, so now there are unstaged changes in the git checkout. The next time you provision, the git pull fails due to unstaged changes.

Would it be better to install wp-cli using the normal install method as suggested here: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/82#issuecomment-19367345?

### PR DESCRIPTION
**Pull request by jjeaton**
Previously, VVV was cloning the wp-cli repo and installing
composer dependencies. This switches to the standard wp-cli
installation method which will make updating wp-cli easier.

`wp cli update` will run on re-provision.

Users can run `wp cli update` at any time
or `wp cli update --nightly` to update to the latest nightly.

Fixes #983.

### CODE REVIEW

File: provision/provision.sh [hunk 1]
```diff
@@ -559,19 +559,18 @@ services_restart() {
...
-    composer install
+    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
+    chmod +x wp-cli.phar
+    sudo mv wp-cli.phar /usr/local/bin/wp
   else
     echo -e "\nUpdating wp-cli..."
-    cd /srv/www/wp-cli
-    git pull --rebase origin master
-    composer install
+    wp cli update --yes
```
Comment (LoreleiAurora) [inline provision/provision.sh]: Can you change this to the nightly instead.
This way if there are any changes in WP Develop/Trunk they will be patched in CLI quicker.

File: provision/provision.sh [hunk 2]
```diff
@@ -559,19 +559,18 @@ services_restart() {
...
-  if [[ ! -d "/srv/www/wp-cli" ]]; then
+  local exists_wpcli
+
+  exists_wpcli="$(which wp)"
+  if [[ "/usr/local/bin/wp" != "${exists_wpcli}" ]]; then
     echo -e "\nDownloading wp-cli, see http://wp-cli.org"
-    git clone "https://github.com/wp-cli/wp-cli.git" "/srv/www/wp-cli"
-    cd /srv/www/wp-cli
-    composer install
+    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
```
Comment (LoreleiAurora) [inline provision/provision.sh]: As below

File: provision/provision.sh (hunk 1 above)
Comment (jjeaton) [inline provision/provision.sh]: Yep, good call.

File: provision/provision.sh [hunk 3]
```diff
@@ -559,19 +559,18 @@ services_restart() {
...
-    composer install
+    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar
+    chmod +x wp-cli.phar
+    sudo mv wp-cli.phar /usr/local/bin/wp
   else
     echo -e "\nUpdating wp-cli..."
-    cd /srv/www/wp-cli
-    git pull --rebase origin master
-    composer install
+    wp cli update --nightly --yes
```
Comment (jeremyfelt) [inline provision/provision.sh]: What happens here if provisioning is run on a setup that was previously using the `git` clone?

Comment (LoreleiAurora) [inline provision/provision.sh]: It wouldnt work, but neither will most of the changes in v2

**Comment by LoreleiAurora** [comment]
Bash completion will not work with this, If you are unsure how to repair this allow commits from maintainers and i can jump in and fix this.

**Comment by jjeaton** [comment]
@LoreleiAurora edits should be allowed. Yeah I wasn't sure how to handle provisioning existing installs.

I'm happy to take a stab at fixing the completions as well, but if you are raring to go on it right now, feel free! 😄

File: provision/provision.sh (hunk 3 above)
Comment (jjeaton) [inline provision/provision.sh]: Would we want to add a check for the `/srv/www/wpcli` dir and attempt the earlier version of the upgrade here if it exists instead?

**Comment by LoreleiAurora** [comment]
Im on mobile, so cant do that now :)

File: provision/provision.sh (hunk 3 above)
Comment (LoreleiAurora) [inline provision/provision.sh]: If we add something like:
```
if [[ -L "/usr/local/bin/wp" ]]; then
  echo "Removing old wp-cli"
  rm -rf /usr/local/bin/wp /srv/www/wp-cli
fi
```
before `if [[ "/usr/local/bin/wp" != "${exists_wpcli}" ]]; then` it should migrate people seemlessly.

THE ABOVE SNIPPET IS UNTESTED.

**Comment by jjeaton** [comment]
Added installation of wpcli bash completions and updating them. Although I'm not sure whether it should be redownloaded on every provision, as that file has only had one change in 2 years?

I can look more into how we can upgrade existing users later on.

**Comment by LoreleiAurora** [comment]
@jjeaton i added a comment [further up](https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1057#discussion_r92657841) explaining how i would do it.

File: provision/provision.sh (hunk 3 above)
Comment (jeremyfelt) [inline provision/provision.sh]: I'd like to see if we can look for `/srv/www/wp-cli/.git` if `/usr/local/bin/wp` exists and then reinstall with the phar. We can include - remove `/srv/www/wp-cli` - as part of the upgrade instructions, but it would be nice if it accounted for this as an upgrade procedure.

Comment (LoreleiAurora) [inline provision/provision.sh]: My snippet above only does rm if /usr/local/bin/wp is a symlink, does that not achieve tha same goal?

Comment (jeremyfelt) [inline provision/provision.sh]: Huh, GitHub was hiding your previous comment from me before. :)

That should do the trick, though I'd leave `/srv/www/wp-cli/` alone just in case somebody was using that to contribute and had branches.

Comment (jjeaton) [inline provision/provision.sh]: I'll make this change and test 👍

**Comment by jjeaton** [comment]
@LoreleiAurora updated to remove just the wp symlink if it exists, so existing users get upgraded to the standard install, silenced the curl requests, and removing the updating of the bash completions.

I've squashed the commits and this is ready for review again.
