### PR TITLE
Fix potentially broken nginx_upstream.

### LINKED ISSUE #2028: Validate Nginx Upstream values
At the moment you can specify a different version of PHP like this:

```yaml
nginx_upstream: php73
```

But there's nothing validating that `php73` actually exists, and a user could put in nonsensical values such as:

```yaml
nginx_upstream: banana
```

The end result is a provision failure without any explanation

### PR DESCRIPTION
**Pull request by msaggiorato**
This fixes #2028.

Accepts php or any valid upstream in the /etc/nginx/upstreams directory.

Example output:

image

### CODE REVIEW

File: provision/provision-site.sh [hunk 1]
```diff
@@ -76,6 +76,11 @@ function vvv_provision_site_nginx() {
   sed -i "s#{vvv_path_to_site}#${VM_DIR}#" "/etc/nginx/custom-sites/${DEST_NGINX_FILE}"
   sed -i "s#{vvv_site_name}#${SITE}#" "/etc/nginx/custom-sites/${DEST_NGINX_FILE}"
   sed -i "s#{vvv_hosts}#${VVV_HOSTS}#" "/etc/nginx/custom-sites/${DEST_NGINX_FILE}"
+
+  if [ 'php' != "${NGINX_UPSTREAM}" ] && [ ! -f "/etc/nginx/upstreams/${NGINX_UPSTREAM}.conf" ]; then
+    echo -e "${YELLOW} * Upstream ${NGINX_UPSTREAM} not found. Defaulting to php.${CRESET}"
+    NGINX_UPSTREAM='php'
```
Comment (tomjn) [inline provision/provision-site.sh]: There is no `php` upstream, instead it should default to `php72` as that's what VVV core installs. We should also print out a list of the valid nginx upstream values

File: provision/provision-site.sh [hunk 2]
```diff
@@ -76,6 +76,11 @@ function vvv_provision_site_nginx() {
   sed -i "s#{vvv_path_to_site}#${VM_DIR}#" "/etc/nginx/custom-sites/${DEST_NGINX_FILE}"
   sed -i "s#{vvv_site_name}#${SITE}#" "/etc/nginx/custom-sites/${DEST_NGINX_FILE}"
   sed -i "s#{vvv_hosts}#${VVV_HOSTS}#" "/etc/nginx/custom-sites/${DEST_NGINX_FILE}"
+
+  if [ 'php' != "${NGINX_UPSTREAM}" ] && [ ! -f "/etc/nginx/upstreams/${NGINX_UPSTREAM}.conf" ]; then
```
Comment (tomjn) [inline provision/provision-site.sh]: We don't need the first bit as `php` isn't a valid upstream value, just the final file check for the `.conf` file is enough

Comment (tomjn) [inline provision/provision-site.sh]: I think this should do the trick:

```suggestion
  if [ ! -f "/etc/nginx/upstreams/${NGINX_UPSTREAM}.conf" ]; then
```

File: provision/provision-site.sh (hunk 1 above)
Comment (tomjn) [inline provision/provision-site.sh]:
```suggestion
    NGINX_UPSTREAM='php72'
```

File: provision/provision-site.sh [hunk 3]
```diff
@@ -76,6 +76,11 @@ function vvv_provision_site_nginx() {
...
+    echo -e "${YELLOW} * Upstream ${NGINX_UPSTREAM} not found. Defaulting to php.${CRESET}"
```
Comment (tomjn) [inline provision/provision-site.sh]:
```suggestion
    echo -e "${YELLOW} * Upstream value '${NGINX_UPSTREAM}' doesn't match a valid upstream. Defaulting to 'php72'.${CRESET}"
```

File: provision/provision-site.sh (hunk 1 above)
Comment (msaggiorato) [reply provision/provision-site.sh]: There is a php upstream. Checked it personally.

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/nginx-config/nginx.conf#L88-L91

Comment (msaggiorato) [reply provision/provision-site.sh]: It's also the default upstream https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L189

File: provision/provision-site.sh (hunk 2 above)
Comment (msaggiorato) [reply provision/provision-site.sh]: I initially had it like this, but covered for php, since that was the default in Vagrantfile. (read other thread for context and links to references)

Comment (tomjn) [reply provision/provision-site.sh]: hmmm perhaps we need to double check `php` works as a value
